apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: mongodb-secret # secret gets created with this name
    creationPolicy: Owner
  dataFrom:
    extract:
      - key: mongodb-secret
        property: mongodb-username
        name: mongodb-username
      - key: mongodb-secret
        property: mongodb-password
        name: mongodb-password
