- name: Add repos (persistent)
  command: helm repo add argo https://artifacthub.io/packages/helm/argo/argo-cd

- name: Install ArgoCD with Helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    

