apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-lb-controller
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    helm:
      releaseName: aws-lb-controller
      valuesObject:
        clusterName: gp_eks_cluster
        serviceAccount:
          create: true
          name: aws-lb-controller-sa
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::991424600343:role/gp_lb_controller_role
        region: us-east-1
        vpcTags:
          Name: gp_vpc
  
  destination:
    server: https://kubernetes.default.svc
    namespace: aws-lb-controller
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
