apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 991424600343.dkr.ecr.us-east-1.amazonaws.com/frontend-app
        ports:
        - containerPort: 80
        resources:
           limits:
             cpu: "0.5"
             memory: "512Mi"
           requests:
              cpu: "0.1"
              memory: "128Mi"
        env:
         - name: REACT_APP_API_URL
           value: "http://backend:3000"  # Using the ClusterIP service DNS name
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP  
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend
