apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-lb-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    helm:
      releaseName: aws-lb-controller
      valuesObject:
        clusterName: gp-eks-cluster
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::991424600343:role/aws-lb-controller-role
        region: us-east-1
        vpcTages:
          Name: gp_vpc
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
