apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.17.0
    helm:
      releaseName: external-secrets
      valuesObject:
        serviceAccount:
          create: true
          name: external-secrets-sa
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::991424600343:role/eks-eso-role

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
