apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-image-updater-secret
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: git-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: git-creds
        property: username
    - secretKey: password
      remoteRef:
        key: git-creds
        property: password
