pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: kaniko-sa
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - "9999999"
"""
    }
  }

  environment {
    AWS_REGION = 'us-east-1'
    ECR_REGISTRY = '991424600343.dkr.ecr.us-east-1.amazonaws.com'
    IMAGE_REPO = 'backend-app'
    IMAGE_TAG = "1.${BUILD_NUMBER}"
    IMAGE = "${ECR_REGISTRY}/${IMAGE_REPO}:${IMAGE_TAG}"
  }

  stages {
    stage('Checkout Code') {
      steps {
        git branch: 'haroon-backend', url: 'https://github.com/MuhanedAhmed/Full-GitOps-Pipeline-on-AWS-with-Terraform-and-Secrets-Management'
      }
    }

    stage('Build & Push Backend Image') {
      steps {
        container('kaniko') {
          sh '''
          /kaniko/executor \
            --context `pwd`/BackEnd-Part \
            --dockerfile `pwd`/BackEnd-Part/Dockerfile \
            --destination=$IMAGE \
            --verbosity=info \
            --insecure \
            --skip-tls-verify
          '''
        }
      }
    }
  }
}
