pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: kaniko-sa
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - "9999999"
"""
    }
  }

  environment {
    AWS_REGION = 'us-east-1'
    ECR_REGISTRY = '991424600343.dkr.ecr.us-east-1.amazonaws.com'
    IMAGE_REPO = 'frontend-app'
    IMAGE_TAG = "v1.${BUILD_NUMBER}"
    IMAGE = "${ECR_REGISTRY}/${IMAGE_REPO}:${IMAGE_TAG}"
  }

  stages {
    stage('Checkout Code') {
      steps {
        git 'https://github.com/mahmoud254/jenkins_nodejs_example'
      }
    }

    stage('Build & Push Image with Kaniko') {
      steps {
        container('kaniko') {
          sh '''
          /kaniko/executor \
            --context `pwd` \
            --dockerfile `pwd`/dockerfile \
            --destination=$IMAGE \
            --verbosity=info \
            --insecure \
            --skip-tls-verify
          '''
        }
      }
    }
  }
}
