pipeline {
  agent {
    kubernetes {
      label 'kaniko-agent'
      yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  restartPolicy: Never

  volumes:
    - name: workspace-volume
      emptyDir: {}

  initContainers:
    - name: git-clones
      image: alpine/git
      command:
        - sh
        - -c
        - git clone https://github.com/mahmoud254/jenkins_nodejs_example.git /workspace/jenkins_nodejs_example
      volumeMounts:
        - name: workspace-volume
          mountPath: /workspace

  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - sleep
        - infinity
      volumeMounts:
        - name: workspace-volume
          mountPath: /workspace
        - name: kaniko-secret
          mountPath: /kaniko/.docker

  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-docker-config
"""
    }
  }

  environment {
    IMAGE = 'YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/YOUR_REPO:latest'
  }

  stages {
    stage('Build & Push Image with Kaniko') {
      steps {
        container('kaniko') {
          sh '''
          
           
          '''
        }
      }
    }
  }
}
