- name: Add repos (persistent)
  command: helm repo add argo https://argoproj.github.io/argo-helm

- name: Install ArgoCD with Helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    values:
      configs:
        secret:
          argocdServerAdminPassword: $2a$10$vPq/euiNH1Hur5ZQ9gIkuuRw5uDEOK6CUgcvsw5.9MkGdabhRhMIu

- name: Install Argo Image Updater with kubectl
  shell: |
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/manifests/install.yaml